In [3]:
import pandas as pd
cleaned_vehicle = pd.read_csv('vehicle_cleaned.csv')
cleaned_crash = pd.read_csv('crash_cleaned.csv')

In [4]:
cleaned_vehicle.head()

,crash_unit_id,crash_record_id,crash_date,unit_no,num_passengers,unit_type,vehicle_id,vehicle_year,vehicle_type,vehicle_category,vehicle_use,travel_direction,maneuver,occupant_cnt,first_contact_point
0,1000001,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,1,NaN,DRIVER,947651.0,NaN,PICKUP,PASSENGER_VEHICLE,UNKNOWN/NA,N,SKIDDING/CONTROL LOSS,1.0,FRONT-LEFT-CORNER
1,1000002,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,2,1.0,DRIVER,947660.0,2020.0,PASSENGER,PASSENGER_VEHICLE,PERSONAL,S,STRAIGHT AHEAD,2.0,SIDE-LEFT-FRONT
2,1000003,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,1,NaN,DRIVER,947657.0,2017.0,PASSENGER,PASSENGER_VEHICLE,UNKNOWN/NA,S,UNKNOWN/NA,1.0,FRONT-RIGHT-CORNER
3,1000004,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,2,NaN,PARKED,947665.0,2020.0,PASSENGER,PASSENGER_VEHICLE,PERSONAL,S,PARKED,0.0,SIDE-LEFT-REAR
4,1000005,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,3,NaN,DRIVER,947670.0,2017.0,SPORT UTILITY VEHICLE (SUV),PASSENGER_VEHICLE,PERSONAL,S,UNKNOWN/NA,1.0,REAR

In [5]:
cleaned_crash.head()

,crash_record_id,crash_date,crash_year,crash_month,crash_hour,crash_weekday,is_weekend,weather_condition,lighting_condition,roadway_surface_cond,...,traffic_control_device,trafficway_type,first_crash_type,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injury_level,severe_crash
0,000c4307d8e9b39075cffdd0aade3603e0f96f14e41da9...,2025-01-14 12:25:00,2025,1,12,Tuesday,0,SNOW,DAYLIGHT,SNOW OR SLUSH,...,TRAFFIC SIGNAL,DIVIDED - W/MEDIAN (NOT RAISED),SIDESWIPE SAME DIRECTION,IMPROPER TURNING/NO SIGNAL,2,NO INDICATION OF INJURY,0.0,0.0,NO_INJURY,0
1,0b5603954d84b7341c7cad4f570ea039e85919f3750ccb...,2025-05-23 09:15:00,2025,5,9,Friday,0,CLEAR,DAYLIGHT,DRY,...,NO CONTROLS,NOT DIVIDED,PEDALCYCLIST,UNKNOWN,2,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1
2,00bce77960c2faa2a8782a8cac1d6e5715802d6c072a08...,2025-01-14 08:00:00,2025,1,8,Tuesday,0,SNOW,DAYLIGHT,WET,...,TRAFFIC SIGNAL,FOUR WAY,REAR END,FOLLOWING TOO CLOSELY,2,NO INDICATION OF INJURY,0.0,0.0,NO_INJURY,0
3,00c9dee322dcb3d698739f1b452dfda4453e3120ab41a7...,2025-01-14 13:44:00,2025,1,13,Tuesday,0,CLEAR,DAYLIGHT,DRY,...,STOP SIGN/FLASHER,NOT DIVIDED,PARKED MOTOR VEHICLE,UNKNOWN,2,NO INDICATION OF INJURY,0.0,0.0,NO_INJURY,0
4,08ff52c023f6f1723a14b5e459539509b6c8c3db63d46d...,2025-03-16 23:22:00,2025,3,23,Sunday,1,CLEAR,"DARKNESS, LIGHTED ROAD",DRY,...,TRAFFIC SIGNAL,DIVIDED - W/MEDIAN (NOT RAISED),ANGLE,DISREGARDING TRAFFIC SIGNALS,2,NO INDICATION OF INJURY,0.0,0.0,NO_INJURY,0

In [6]:
cleaned_vehicle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 382862 entries, 0 to 382861
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   crash_unit_id        382862 non-null  int64
 1   crash_record_id      382862 non-null  object
 2   crash_date           382862 non-null  object
 3   unit_no              382862 non-null  int64
 4   num_passengers       56502 non-null   float64
 5   unit_type            382859 non-null  object
 6   vehicle_id           382862 non-null  float64
 7   vehicle_year         318551 non-null  float64
 8   vehicle_type         382862 non-null  object
 9   vehicle_category     382862 non-null  object
 10  vehicle_use          382862 non-null  object
 11  travel_direction     352097 non-null  object
 12  maneuver             382862 non-null  object
 13  occupant_cnt         382862 non-null  float64
 14  first_contact_point  382862 non-null  object
dtypes: float64(4), int64(2), object(9)
memory usage: 43.8+ MB

In [7]:
cleaned_crash.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793246 entries, 0 to 793245
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   crash_record_id          793246 non-null  object
 1   crash_date               793246 non-null  object
 2   crash_year               793246 non-null  int64
 3   crash_month              793246 non-null  int64
 4   crash_hour               793246 non-null  int64
 5   crash_weekday            793246 non-null  object
 6   is_weekend               793246 non-null  int64
 7   weather_condition        793246 non-null  object
 8   lighting_condition       793246 non-null  object
 9   roadway_surface_cond     793246 non-null  object
 10  posted_speed_limit       793246 non-null  int64
 11  traffic_control_device   793246 non-null  object
 12  trafficway_type          793246 non-null  object
 13  first_crash_type         793246 non-null  object
 14  prim_contributory_cause  793246 non-null  object
 15  num_units                793246 non-null  int64
 16  most_severe_injury       793246 non-null  object
 17  injuries_total           793246 non-null  float64
 18  injuries_fatal           793246 non-null  float64
 19  injury_level             793246 non-null  object
 20  severe_crash             793246 non-null  int64
dtypes: float64(2), int64(7), object(12)
memory usage: 127.1+ MB

In [9]:
merged = cleaned_vehicle.merge(
    cleaned_crash,
    on='crash_record_id',
    how='left'
)
merged.head()

,crash_unit_id,crash_record_id,crash_date_x,unit_no,num_passengers,unit_type,vehicle_id,vehicle_year,vehicle_type,vehicle_category,...,traffic_control_device,trafficway_type,first_crash_type,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injury_level,severe_crash
0,1000001,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,1,NaN,DRIVER,947651.0,NaN,PICKUP,PASSENGER_VEHICLE,...,NO CONTROLS,NOT DIVIDED,SIDESWIPE OPPOSITE DIRECTION,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1.0
1,1000002,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,2,1.0,DRIVER,947660.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,NOT DIVIDED,SIDESWIPE OPPOSITE DIRECTION,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1.0
2,1000003,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,1,NaN,DRIVER,947657.0,2017.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1.0
3,1000004,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,2,NaN,PARKED,947665.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1.0
4,1000005,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,3,NaN,DRIVER,947670.0,2017.0,SPORT UTILITY VEHICLE (SUV),PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1.0

In [10]:
merged['severe_crash'] = (
    (merged['injuries_total'] > 0) | (merged['injuries_fatal'] > 0)
).astype(int)
merged.head()

,crash_unit_id,crash_record_id,crash_date_x,unit_no,num_passengers,unit_type,vehicle_id,vehicle_year,vehicle_type,vehicle_category,...,traffic_control_device,trafficway_type,first_crash_type,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injury_level,severe_crash
0,1000001,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,1,NaN,DRIVER,947651.0,NaN,PICKUP,PASSENGER_VEHICLE,...,NO CONTROLS,NOT DIVIDED,SIDESWIPE OPPOSITE DIRECTION,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1
1,1000002,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,2,1.0,DRIVER,947660.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,NOT DIVIDED,SIDESWIPE OPPOSITE DIRECTION,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1
2,1000003,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,1,NaN,DRIVER,947657.0,2017.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1
3,1000004,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,2,NaN,PARKED,947665.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1
4,1000005,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,3,NaN,DRIVER,947670.0,2017.0,SPORT UTILITY VEHICLE (SUV),PASSENGER_VEHICLE,...,NO CONTROLS,DIVIDED - W/MEDIAN (NOT RAISED),PARKED MOTOR VEHICLE,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1

In [11]:
merged['vehicle_age'] = merged['crash_year'] - merged['vehicle_year']
merged['passenger_group'] = pd.cut(
    merged['num_passengers'],
    bins=[-1, 0, 2, 5, 100],
    labels=['0', '1-2', '3-5', '5+']
)
merged['vehicle_type_group'] = merged['vehicle_type'].replace({
    'PASSENGER': 'car',
    'SUV': 'car',
    'TRUCK': 'truck',
    'MOTORCYCLE': 'motorcycle'
})
merged.head()

,crash_unit_id,crash_record_id,crash_date_x,unit_no,num_passengers,unit_type,vehicle_id,vehicle_year,vehicle_type,vehicle_category,...,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injury_level,severe_crash,vehicle_age,passenger_group,vehicle_type_group
0,1000001,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,1,NaN,DRIVER,947651.0,NaN,PICKUP,PASSENGER_VEHICLE,...,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1,NaN,NaN,PICKUP
1,1000002,57945047eb951f4152fde013708fa029caf5d33fc2a2c2...,2020-11-25 17:46:00,2,1.0,DRIVER,947660.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,WEATHER,2.0,"REPORTED, NOT EVIDENT",1.0,0.0,REPORTED_NOT_EVIDENT,1,0.0,1-2,car
2,1000003,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,1,NaN,DRIVER,947657.0,2017.0,PASSENGER,PASSENGER_VEHICLE,...,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1,3.0,NaN,car
3,1000004,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,2,NaN,PARKED,947665.0,2020.0,PASSENGER,PASSENGER_VEHICLE,...,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1,0.0,NaN,car
4,1000005,7cf1e0da7413f35c258ad67a3f0d08b10c9cf94a59bb4e...,2020-11-25 18:39:00,3,NaN,DRIVER,947670.0,2017.0,SPORT UTILITY VEHICLE (SUV),PASSENGER_VEHICLE,...,UNKNOWN,3.0,NONINCAPACITATING INJURY,1.0,0.0,NON_INCAPACITATING,1,3.0,NaN,SPORT UTILITY VEHICLE (SUV)

In [15]:
print(len(merged), len(cleaned_vehicle))
print(merged.duplicated().sum())
print(merged.isnull().sum())

382862 382862
0
crash_unit_id                   0
crash_record_id                 0
crash_date_x                    0
unit_no                         0
num_passengers             326360
unit_type                       3
vehicle_id                      0
vehicle_year                64311
vehicle_type                    0
vehicle_category                0
vehicle_use                     0
travel_direction            30765
maneuver                        0
occupant_cnt                    0
first_contact_point             0
crash_date_y                40809
crash_year                  40809
crash_month                 40809
crash_hour                  40809
crash_weekday               40809
is_weekend                  40809
weather_condition           40809
lighting_condition          40809
roadway_surface_cond        40809
posted_speed_limit          40809
traffic_control_device      40809
trafficway_type             40809
first_crash_type            40809
prim_contributory_cause     40809
num_units                   40809
most_severe_injury          40809
injuries_total              40809
injuries_fatal              40809
injury_level                40809
severe_crash                    0
vehicle_age                 93942
passenger_group            326360
vehicle_type_group              0
dtype: int64

In [16]:
print(cleaned_vehicle.isnull().sum())

crash_unit_id               0
crash_record_id             0
crash_date                  0
unit_no                     0
num_passengers         326360
unit_type                   3
vehicle_id                  0
vehicle_year            64311
vehicle_type                0
vehicle_category            0
vehicle_use                 0
travel_direction        30765
maneuver                    0
occupant_cnt                0
first_contact_point         0
dtype: int64

In [17]:
print(merged[merged['crash_year'].isna()].shape)
print(merged[merged['crash_year'].isna()]['crash_record_id'].nunique())

(40809, 38)
20656

In [18]:
unmatched = cleaned_vehicle.loc[
    ~cleaned_vehicle['crash_record_id'].isin(cleaned_crash['crash_record_id'])
]

print(len(unmatched))
print(unmatched['crash_record_id'].nunique())

40809
20656

In [19]:
merged.to_csv('merged_data.csv', index=False)